Fix unregister bug when no disposing function provided
When call unregister with no disposing function, then call of disposingFunction is not checked, throwing NoSuchMethodError: The method 'call' was called on null.

Steps to reproduce:

GetIt.I.registerSingleton("Value");
try {
  GetIt.I.unregister<String>();
} catch (ex) {
  print(ex); // NoSuchMethodError: The method 'call' was called on null.
}